### PR TITLE
fix(Menu): avoid tranforming single child to array while processing menu children

### LINKED ISSUE #2129: menu 内使用Popover 会报错
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.51.1
- **Browser:** chrome115.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/icy-dust-ssgyjw?file=/demo.js

### PR DESCRIPTION
**Pull request by MisterLuffy**
## Types of changes

- [ ] New feature
- [x] Bug fix
- [ ] Enhancement
- [ ] Documentation change
- [ ] Coding style change
- [ ] Component style change
- [ ] Refactoring
- [ ] Test cases
- [ ] Continuous integration
- [ ] Typescript definition change
- [ ] Breaking change
- [ ] Others 

## Changelog

| Component | Changelog(CN) | Changelog(EN) | Related issues |
| --------- | ------------- | ------------- | -------------- |
|    Menu   |   修复 `Popover` 作为 `Menu` 直接子节点报错的问题。  |   Fix the problem that `Popover` is reported as a direct child node of `Menu`.   |   Close #2129    |

## Checklist:

- [ ] Test suite passes (`npm run test`)
- [ ] Provide changelog for relevant changes (e.g. bug fixes and new features) if applicable.
- [ ] Changes are submitted to the appropriate branch (e.g. features should be submitted to `feature` branch and others should be submitted to `main` branch)

### CODE REVIEW

File: components/Menu/util.ts [hunk 1]
```diff
@@ -96,10 +96,11 @@ export const processChildren = (
     // 处理 <div> 包裹 MenuItem 之类的情况
     if (!isMenuSubComponent && item.props.children) {
       const _props = isHTMLElement ? {} : props;
+      const itemChildrenList = processChildren(item.props.children, props);
       return React.cloneElement(item, {
         ..._props,
         _key: item.key,
-        children: processChildren(item.props.children, props),
+        children: itemChildrenList.length === 1 ? itemChildrenList[0] : itemChildrenList,
```
Comment (yinkaihui) [inline components/Menu/util.ts:103]: children 是数组，但元素只有一个和只有一个 children 的情况需要区分不 ？
image

**Review by yinkaihui — APPROVED** [review]
