### PR TITLE
fix: 修复[Upload]: duplicate uid警告出现的时机

### LINKED ISSUE #1780: Upload 错误的警告 duplicate uid
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.44.3
- **Browser:** chrome110.0.0.0

## Steps to reproduce
Upload 上传组件

https://github.com/arco-design/arco-design/blob/ba0bee0385533cb36c7af0de63da2d27fd4aec1f/components/Upload/upload.tsx#L25

warning出现的位置感觉应该在，repeatUidIndex 不等于 -1的地方吧？

### PR DESCRIPTION
**Pull request by motopods**
## Types of changes

- [ ] New feature
- [x] Bug fix
- [ ] Enhancement
- [ ] Documentation change
- [ ] Coding style change
- [ ] Component style change
- [ ] Refactoring
- [ ] Test cases
- [ ] Continuous integration
- [ ] Typescript definition change
- [ ] Breaking change
- [ ] Others 

## Background and context

[Upload]: duplicate uid警告的判断不正确，导致正常情况下也触发警告。

https://github.com/arco-design/arco-design/issues/1780

## Solution

调整warning的位置

## Changelog

| Component | Changelog(CN) | Changelog(EN) | Related issues |
| --------- | ------------- | ------------- | -------------- |
|    Upload        |    修复 `Upload` 组件校验重复 `uid` 警告逻辑异常           |    Fix `Upload` component verification duplicate `uid` warning logic exception         | Close #1780        |

## Checklist:

- [x] Test suite passes (`npm run test`)
- [x] Provide changelog for relevant changes (e.g. bug fixes and new features) if applicable.
- [x] Changes are submitted to the appropriate branch (e.g. features should be submitted to `feature` branch and others should be submitted to `main` branch)

### CODE REVIEW

File: components/Upload/upload.tsx [hunk 1]
```diff
@@ -31,6 +30,7 @@ const processFile = function (fileList?: UploadItem[]): UploadItem[] {
       if (repeatUidIndex === -1) {
         total.push(item);
       } else {
+        warning(repeatUidIndex, '[Upload]: duplicate uid');
```
Comment (yinkaihui) [inline components/Upload/upload.tsx:33]: 直接在原本的基础上 warning(repeatUidIndex === -1, '[Upload]: duplicate uid'); 就行
当前这样修改的话， repeatUidIndex = 0 时，不会提示

Comment (motopods) [reply components/Upload/upload.tsx]: 抱歉忽略了warning函数的实现。应该是repeatUidIndex !== -1吧？ 已经更新提交

**Review by yinkaihui — APPROVED** [review]
